name: rx_bloc
description: A Flutter package that helps implementing the BLoC (Business Logic Component) Design Pattern using the power of reactive streams.
version: 3.3.1
repository: https://github.com/Prime-Holding/rx_bloc/tree/master/packages/rx_bloc
issue_tracker: https://github.com/Prime-Holding/rx_bloc/issues
homepage: https://www.primeholding.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  meta: ^1.7.0
  rxdart: ^0.27.3

dev_dependencies:
  clean_coverage: ^0.0.3
  coverage: ^1.3.2
  flutter_lints: ^1.0.4
  mockito: ^5.0.17
  quiver: ^3.0.1
  rx_bloc_test: ^3.2.0
  test: ^1.18.2

dependency_overrides:
  rx_bloc_test:
    path: ../rx_bloc_test
