name: rx_bloc
description: A Flutter package that helps implementing the BLoC (Business Logic Component) Design Pattern using the power of reactive streams.
version: 3.1.0
repository: https://github.com/Prime-Holding/rx_bloc/tree/master/packages/rx_bloc
issue_tracker: https://github.com/Prime-Holding/rx_bloc/issues
homepage: https://www.primeholding.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  rxdart: ^0.27.2
  collection: ^1.15.0
  meta: ^1.7.0

dev_dependencies:
  rx_bloc_test: 3.0.0
  pedantic: ^1.11.1
  test: ^1.17.12
  mockito: ^5.0.16
  quiver: ^3.0.1
  coverage: ^1.0.3
  clean_coverage: ^0.0.3

dependency_overrides:
  rx_bloc_test:
    path: ../rx_bloc_test
