name: example
description: RxBloc example
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart:
  rx_bloc:
  flutter_rx_bloc:

dev_dependencies:
  rx_bloc_generator:
  build_runner:
  rx_bloc_test: ^0.0.3
  flutter_test:
    sdk: flutter

dependency_overrides:
  rx_bloc_test:
    path: ../../packages/rx_bloc_test
  rx_bloc:
    path: ../../packages/rx_bloc
  flutter_rx_bloc:
    path: ../../packages/flutter_rx_bloc
  rx_bloc_generator:
    path: ../../packages/rx_bloc_generator


flutter:

#  assets:
#    - images/a_dot_burr.jpeg

