name: rx_bloc_list
description: The rx_bloc_list package facilitates implementing infinity scroll and pull-to-refresh features with minimal setup. This package is meant to be used along with RxBloc ecosystem.
version: 3.2.0-dev.1
homepage: https://www.primeholding.com
repository: https://github.com/Prime-Holding/rx_bloc/tree/master/packages/rx_bloc_list
issue_tracker: https://github.com/Prime-Holding/rx_bloc/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_rx_bloc: ^4.0.0
  rx_bloc: ^3.2.0
  rxdart: ^0.27.2


dev_dependencies:
  build_runner: ^2.1.2
  clean_coverage: ^0.0.3
  coverage: ^1.3.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  rx_bloc_generator: ^5.1.0


flutter:
  uses-material-design: true

dependency_overrides:
  flutter_rx_bloc:
    path: ../flutter_rx_bloc
  rx_bloc:
    path: ../rx_bloc
  rx_bloc_generator:
    path: ../rx_bloc_generator

