name: rx_bloc_test
description: A Flutter package with the goal to enable testing rxBlocs from the FlutterRxBloc package with ease.
version: 3.2.0
repository: https://github.com/Prime-Holding/rx_bloc/tree/master/packages/rx_bloc_test
issue_tracker: https://github.com/Prime-Holding/rx_bloc/issues
homepage: https://primeholding.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.7.0
  rx_bloc: ^3.2.0
  rxdart: ^0.27.3
  test: ^1.17.0

dev_dependencies:
  clean_coverage: ^0.0.3
  coverage: ^1.3.2
  flutter_lints: ^1.0.4
  mockito: ^5.0.16
  pedantic: ^1.11.1

dependency_overrides:
  rx_bloc:
    path: ../rx_bloc
