name: rx_bloc_test
description: A Flutter package with the goal to enable testing rxBlocs from the FlutterRxBloc package with ease.
version: 1.0.1
repository: https://github.com/Prime-Holding/rx_bloc/tree/master/packages/rx_bloc_test
issue_tracker: https://github.com/Prime-Holding/rx_bloc/issues
homepage: https://primeholding.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  test: ^1.15.0
  rxdart: ^0.26.0
  rx_bloc: ^2.0.0
  meta: ^1.2.0
  quiver: ^3.0.0

dev_dependencies:
  pedantic: ^1.9.0
  mockito: ^5.0.0


dependency_overrides:
  rx_bloc:
    path: ../rx_bloc
