name: rx_bloc_generator
description: Code generator for rx_bloc that makes your BloC zero-boilerplate.
version: 3.0.2
repository: https://github.com/Prime-Holding/rx_bloc/tree/master/packages/rx_bloc_generator
issue_tracker: https://github.com/Prime-Holding/rx_bloc/issues
homepage: https://www.primeholding.com/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  logging: ^1.0.0
  source_gen: ">=0.9.10 <2.0.0"
  dart_style: ">=1.3.0 <3.0.0"
  analyzer: ">=0.41.0 <2.0.0"
  build: ^2.0.0
  rx_bloc: ^3.0.0
  code_builder: ^3.7.0
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.9.2
  build_runner: ^1.11.1
  test: ^1.16.0
  source_gen_test: any
  coverage: ^1.0.0
  clean_coverage: ^0.0.3


#dependency_overrides:
#  rx_bloc:
#    path: ../rx_bloc
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
#flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
