name: rx_bloc_generator
description: Code generator for rx_bloc that makes your BloC zero-boilerplate.
version: 6.1.0
repository: https://github.com/Prime-Holding/rx_bloc/tree/master/packages/rx_bloc_generator
issue_tracker: https://github.com/Prime-Holding/rx_bloc/issues
homepage: https://www.primeholding.com/

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  analyzer: ">=5.13.0 <6.0.0"
  build: ^2.4.0
  code_builder: ^4.5.0
  collection: ^1.17.1
  dart_style: ">=2.3.1 <3.0.0"
  logging: ^1.2.0
  rx_bloc: ^4.1.0
  source_gen: ">=1.3.2 <2.0.0"

dev_dependencies:
  build_runner: ^2.4.5
  clean_coverage: ^0.0.3
  coverage: ^1.6.3
  flutter_lints: ^2.0.1
  source_gen_test: ^1.0.5
  test: ^1.24.1
