name: booking_app
description: A demo app showcasing booking functionality
publish_to: none
version: 1.0.0+2

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  animated_stream_list:
  appbar_textfield: ^1.0.1+1
  badges: ^1.1.4
  collection: ^1.15.0-nullsafety.4
  cupertino_icons: ^1.0.0
  curved_navigation_bar: ^1.0.3
  equatable: ^2.0.0
  favorites_advanced_base:
    path: ../favorites_advanced/favorites_advanced_base
  flutter:
    sdk: flutter
  flutter_rx_bloc:
  go_router: ^6.0.9
  image_picker: ^0.8.6
  intl: ^0.17.0
  provider: ^6.0.0
  rflutter_alert: ^2.0.2
  rx_bloc:
  rx_bloc_list:
  rxdart: ^0.27.0

dev_dependencies:
  build_runner: ^2.0.0
  clean_coverage: ^0.0.3
  flutter_lints: any
  flutter_test:
    sdk: flutter
  go_router_builder: ^1.1.0
  golden_toolkit: ^0.14.0
  mockito: ^5.0.0
  quiver: ^3.0.0
  rx_bloc_generator:
  rx_bloc_test: ^3.2.0
  test: any



dependency_overrides:
  rflutter_alert:
    git:
      url: https://github.com/kent2508/rflutter_alert.git
      ref: master
  animated_stream_list:
    git:
      url: https://github.com/nilsreichardt/animated-stream-list.git
      ref: migrate-null-safety
  appbar_textfield:
    git:
      url: https://github.com/StanevPrime/appbar_textfield.git
      ref: null-safety
  badges: 3.0.2
  favorites_advanced_base:
    path: ../favorites_advanced/favorites_advanced_base
  flutter_rx_bloc:
    path: ../../packages/flutter_rx_bloc
  rx_bloc:
    path: ../../packages/rx_bloc
  rx_bloc_generator:
    path: ../../packages/rx_bloc_generator
  rx_bloc_list:
    path: ../../packages/rx_bloc_list
  rx_bloc_test:
    path: ../../packages/rx_bloc_test

  skeleton_text:
    git:
      url: https://github.com/StanevPrime/Skeleton-Text.git
      ref: feature/null-safety
  smooth_star_rating:
    git:
      url: https://github.com/bhavin-concetto/smoothratingbar.git
      ref: dev
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
