name: github_search
description: A new Flutter project.
homepage: https://example.com
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  cupertino_icons: ^1.0.4
  dio: ^4.0.4
  firebase_analytics: ^9.0.4
  firebase_core: ^1.10.6
  firebase_messaging: ^11.2.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.1.5
  flutter_localizations:
    sdk: flutter
  flutter_rx_bloc: ^4.0.0
  flutter_secure_storage: ^5.0.2
  golden_toolkit: ^0.12.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.3
  provider: ^6.0.1
  retrofit: ^3.0.0
  rx_bloc: ^3.2.1
  rx_bloc_list: ^3.1.0
  rxdart: ^0.27.3
  shared_preferences: ^2.0.11

  # Only for testing purposes
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  shelf_static: ^1.1.0

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.7
  # flutter_driver:
  #   sdk: flutter
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  # Only for testing purposes (such as in the local server)
  http: ^0.13.4
  mockito: ^5.0.16

  retrofit_generator: ^3.0.0
  rx_bloc_generator: ^5.1.0
  rx_bloc_test: ^3.2.0
  test: any


dependency_overrides:
  flutter_rx_bloc:
    path: ../../packages/flutter_rx_bloc
  rx_bloc:
    path: ../../packages/rx_bloc
  rx_bloc_generator:
    path: ../../packages/rx_bloc_generator
  rx_bloc_list:
    path: ../../packages/rx_bloc_list
  rx_bloc_test:
    path: ../../packages/rx_bloc_test

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: WorkSans
      fonts:
        - asset: fonts/WorkSans/WorkSans-Light.ttf
          weight: 300
        - asset: fonts/WorkSans/WorkSans-Regular.ttf
          weight: 400
        - asset: fonts/WorkSans/WorkSans-Medium.ttf
          weight: 500
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

