name: rx_bloc_cli
description: "rx_bloc_cli that enables quick project setup including: flavors, localization [intl], state management [rx_bloc], routing [go_router], design system, analytics [firebase], tests"
version: 3.8.0
repository: https://github.com/Prime-Holding/rx_bloc/tree/master/packages/rx_bloc_cli
issue_tracker: https://github.com/Prime-Holding/rx_bloc/issues
homepage: https://www.primeholding.com

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  args: ^2.5.0
  collection: ^1.18.0
  flutter_lints: ^4.0.0
  mason: ^0.1.0-dev.52
  path: ^1.8.3
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.4.6
  clean_coverage: ^0.0.3
  mason_cli: ^0.1.0-dev.54
  mason_logger: ^0.2.12
  mockito: ^5.4.3
  test: ^1.25.2

dependency_overrides:
  pub_semver: ^2.1.4

executables:
  rx_bloc_cli:
