name: rx_bloc_cli
description: "rx_bloc_cli that enables quick project setup including: flavors, localization [intl], state management [rx_bloc], routing [auto_route], design system, analytics [firebase], tests"
version: 0.0.5
repository: https://github.com/Prime-Holding/rx_bloc/tree/master/packages/rx_bloc_cli
issue_tracker: https://github.com/Prime-Holding/rx_bloc/issues
homepage: https://www.primeholding.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.1.1
  io: ^1.0.0
  mason: ^0.0.1-dev.41
  path: ^1.8.0

dev_dependencies:

executables:
  rx_bloc_cli: