name: 'Publish rx_bloc_cli to pub.dev'

on:
  push:
    tags:
      - 'rx_bloc_cli-v[0-9]+.[0-9]+.[0-9]+*'

# Publish using custom workflow
jobs:
  publish:
    name: 'Publish rx_bloc_cli to pub.dev'
    environment: pub.dev
    permissions:
      id-token: write # This is required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: "stable"
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        working-directory: packages/rx_bloc_cli
        run: dart pub get
      - name: Generate bundles
        working-directory: packages/rx_bloc_cli
        run: bin/compile_bundles.sh
      - name: Publish
        working-directory: packages/rx_bloc_cli
        run: dart pub publish --force
